version: '3'
services:
  dwfrontend:
    build: ./developwright/dwfrontend
    ports:
     - "8081:8081"
  dwbackend:
    build: ./developwright/dwbackend
    ports:
      - "8080:8080"
  postgres:
    image: 'postgres:latest'      