services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./acme.json:/acme.json"

  angular-app:
    build:
      context: ./frontend/frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.angular.rule=Host(`developwright.com`)"
      - "traefik.http.services.angular.loadbalancer.server.port=80"
      - "--certificatesresolvers.mytls.acme.email=your-email@example.com"
      - "--certificatesresolvers.mytls.acme.storage=/acme.json"
      - "--certificatesresolvers.mytls.acme.tlschallenge=true"

  dotnet-api:
    build:
      context: ./backend/backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.developwright.com`)"
      - "traefik.http.services.api.loadbalancer.server.port=80"
