version: '3'
services:
  dwbackend:
    build: ./developwright/dwbackend
    ports:
      - "5000:5000"

  dwfrontend:
    image: nginx:alpine
    volumes:
      - .nginx.conf:/etc/nginx/nginx.conf:ro
    build: ./developwright/dwfrontend
    ports:
     - "5173:5173"

  postgres:
    image: 'postgres:latest'      