FROM mcr.microsoft.com/dotnet/aspnet:8.0.8 AS base
WORKDIR /app
EXPOSE 5000

ENV ASPNETCORE_URLS=http://+:5000

RUN dwadmin -u 5678 --disabled-password --gecos "" dwadmin && chown -R dwadmin /backend
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:8.0.108 AS build
WORKDIR /src
COPY ["backend.csproj", "backend.csproj"]
RUN dotnet restore "backend.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "backend.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "backend.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "backend.dll"]